version: 2.1
orbs:
  node: circleci/node@3.0.0
  
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - run: npm run build
        
workflows:
  build:
    jobs:
      - build

