version: 2.1
orbs:
  node: circleci/node@3.0.0
  
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: npm run build
        
workflows:
  build:
    jobs:
      - build

